### PR TITLE
chore: Readme updates, including permissions details

### PR DESCRIPTION
**Pull request by molawson**
There are two main things going on here. Each is represented by a separate commit.

1. General readme updating and clean up.
2. Add a note about getting this action to run with tools like dependabot.

### CODE REVIEW

**Review by sheck — COMMENTED** [review]
I think everything looks great except the removal of the caching suggestion. In our app we're caching about 37mb of `node_modules` and it takes 1 seconds to restore and 1-4 seconds to save. What do you think about re-adding it or re-adding it with a comment along the lines of "may not be useful for all setups"?

**Comment by molawson** [comment]
@sheck In your app, is that 37 MB in `node_modules` for the dependencies that this action installs, or is that the entirety of the JS dependencies for your app? 

It sounds like I may have something fundamentally off, but I thought, based on the readme and implementations for this and other balto actions, that part of the idea was that balto actions are fast because they only install the dependencies they need to run.  If that is the case, caching based on a much larger `yarn.lock` doesn't seem to quite line up.  

I'd imagine that if a workflow is doing more with other actions that require a full `npm install`, that workflow would certainly benefit from caching.  But that seems outside of the concerns of this repo and the "selective install" setup.  Is there something I'm missing here?

**Comment by sheck** [comment]
@molawson the 37mb is just the select few packages that balto installs (and all of _their_ dependencies as well). Our full install is over 750mb. Part of why I think it's useful is because of how fundamentally different npm works from bundler, where packages can have their own versions of their dependencies installed — resulting in potentially have multiple versions of the same dependency in a `node_modules` folder.

I'm totally fine saying it's optional! I just think it's still beneficial to have it listed.

**Comment by molawson** [comment]
@sheck I'm tracking with you now.  Having the caching in the example makes sense then, and I'll add a note about why its there.

**Review by sheck — APPROVED** [review]

**Pull request merged**
