### PR TITLE
🐛🔧 bugfix: Add missing `semver` package

### PR DESCRIPTION
**Pull request by alexandervalencia**
I recently noticed that we're missing a used package (`semver`) from the `package.json`. This is potentially causing an issue that we haven't seen yet as no other teams are using `balto-eslint` beyond version `0.5`

### CODE REVIEW

**Comment by alexandervalencia** [comment]
Ah, that's why it was still working 😅

**Comment by sheck** [comment]
Thanks for looking into this! Could you do the following?

- Run `npm i` so our `package-lock.json` gets updated
- Rebase your branch off of main so the CODEOWNERS commit isn't in your PR

**Comment by alexandervalencia** [comment]
Thanks for the catch @sheck, updated as requested

**Comment by sheck** [comment]
🤔 Hmm the NCC github action should have ran but it didn't. Looking into that right now.

**Review by sheck — APPROVED** [review]

**Pull request merged**
